### ISSUE TITLE
Error: Backend Service Fails Due to Missing Migration Revision '119709b3f9bb' When Accessing localhost/docs After Running Docker

### ISSUE THREAD

**Issue by SureshPradhana** [d4vidsha/scheduler#43]
The backend service throws the following error and stops when I access `localhost/docs`:

```plaintext
backend-1  |   warnings.warn(message, stacklevel=1)
backend-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
backend-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
backend-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '119709b3f9bb'
backend-1  | FAILED: Can't locate revision identified by '119709b3f9bb'
```

Reproduction:

1. **Copy the environment variables:**
   ```bash
   cp .env.example .env
   ```

2. **Run Docker Compose:**
   ```bash
   docker compose up
   ```
3. **Visit `localhost/docs`.**

4. **Check Docker Logs:**
   ```bash
   docker compose logs backend
   ```

**Comment by d4vidsha** [comment]
Hi @SureshPradhana, thanks for making this issue! Could you try `docker compose down -v`, it will delete the entire stack **including the volumes** (which is the main issue here because Alembic is trying to find a revision that doesn't exist and Alembic gets this revision value from a value stored in your local db which is in that Docker volume). This issue is occurring because of a breaking change I made with an earlier commit. Once you've done that, you should be able to `docker compose up` without issues. Let me know how it goes.

Ideally, I shouldn't be making these breaking changes without warning, but since it's a relatively small project at the moment without any releases yet, I just haven't mentioned it anywhere oops 😅 Will be noted for future though.

**Comment by SureshPradhana** [comment]
@d4vidsha 
 I ran `docker compose down -v`, and it fixed the issue. Everything's working fine now. Thanks for the help!
